package(default_visibility = ["//visibility:public"])

cc_library(
    name = "test_helpers",
    srcs = [
        "testing.cpp",
    ],
    hdrs = [
        "testing.h",
    ],
    deps = [
        "//alpaca:alpaca",
        "@com_github_google_googletest//:gtest",
    ],
)
